### ISSUE TITLE
Project does not build: django error

### ISSUE THREAD

**Issue by viktorsmari** [openlab-org/openlab.org#2]
> Collecting django-contact-form==1.3 (from -r /requirements/base.txt (line 60))
  Downloading https://files.pythonhosted.org/packages/a4/48/d6dd28fcf5f9460c071ad1e8c88ce6246d56667e11b8d97683ba6cc8eecf/django-contact-form-1.3.tar.gz (900kB)
Obtaining django-select2 from git+https://github.com/michaelpb/django-select2.git@v4#egg=django-select2 (from -r /requirements/base.txt (line 65))
  Cloning https://github.com/michaelpb/django-select2.git (to revision v4) to /src/django-select2
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/src/django-select2/setup.py", line 23, in <module>
        VERSION = __import__(PACKAGE).__version__
      File "/src/django-select2/django_select2/__init__.py", line 95, in <module>
        from django.conf import settings
    ImportError: No module named 'django'
    
    ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /src/django-select2/
ERROR: Service 'django' failed to build: The command '/bin/sh -c pip install --no-cache-dir -r /requirements/production.txt     && rm -rf /requirements' returned a non-zero code: 1

Same error when using **both** `virtualenv` and `docker-compose`

If I do first `pip install django` then other modules fail installing like 'breadcrumb'

If I run `python manage.py runserver` the error:
> ModuleNotFoundError: No module named 'breadcrumbs'

**Comment by viktorsmari** [comment]
@michaelpb Does the project build OK on your machine?
